import { useNavigate } from 'react-router-dom';
import {
  Shield,
  User,
  Mail,
  Crown,
  Calendar,
  ShieldCheck,
  LogOut,
  ScanFace,
  History,
  Settings,
} from 'lucide-react';
import { useAuth } from '../hooks/useAuth';
import { useAuthStore } from '../store/authStore';

export function DashboardPage() {
  const { user } = useAuthStore();
  const { logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = async () => {
    await logout();
    navigate('/login');
  };

  const initials = user?.name
    ?.split(' ')
    .map((n) => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2) || '??';

  const memberSince = user?.created_at
    ? new Date(user.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long' })
    : 'Unknown';

  return (
    <div className="min-h-screen bg-[#0a0f1e]">
      {/* Navbar */}
      <nav className="sticky top-0 z-50 border-b border-white/5 bg-[#0a0f1e]/80 backdrop-blur-xl">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-600">
              <Shield className="w-4 h-4 text-white" />
            </div>
            <span className="text-lg font-bold text-white">FaceAuth</span>
          </div>
          <div className="flex items-center gap-4">
            {user?.is_admin && (
              <button
                id="btn-admin"
                onClick={() => navigate('/admin')}
                className="btn-ghost text-xs px-3 py-1.5"
              >
                <Settings className="w-3.5 h-3.5" /> Admin
              </button>
            )}
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-full bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center text-sm font-semibold text-white">
                {initials}
              </div>
              <button id="btn-logout" onClick={handleLogout} className="btn-danger text-xs px-3 py-1.5">
                <LogOut className="w-3.5 h-3.5" /> Sign Out
              </button>
            </div>
          </div>
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-6xl mx-auto px-6 py-8 space-y-6">
        {/* Welcome header */}
        <div className="animate-fade-in">
          <h1 className="text-3xl font-bold text-white">
            Welcome, {user?.name?.split(' ')[0] || 'User'}
          </h1>
          <p className="text-[var(--color-text-muted)] mt-1">Your biometric dashboard</p>
        </div>

        {/* Stats grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
          {/* Profile Card */}
          <div className="glass-card p-6 animate-slide-up" style={{ animationDelay: '0.1s' }}>
            <div className="flex items-center gap-3 mb-5">
              <div className="p-2 rounded-lg bg-blue-500/10">
                <User className="w-5 h-5 text-blue-400" />
              </div>
              <h3 className="text-base font-semibold text-white">Profile</h3>
            </div>
            <div className="space-y-3">
              <InfoRow icon={<User className="w-4 h-4" />} label="Name" value={user?.name || '—'} />
              <InfoRow icon={<Mail className="w-4 h-4" />} label="Email" value={user?.email || '—'} />
              <InfoRow icon={<Crown className="w-4 h-4" />} label="Role" value={user?.is_admin ? 'Administrator' : 'User'} />
              <InfoRow icon={<Calendar className="w-4 h-4" />} label="Member since" value={memberSince} />
            </div>
          </div>

          {/* Security Status */}
          <div className="glass-card p-6 md:col-span-2 animate-slide-up" style={{ animationDelay: '0.2s' }}>
            <div className="flex items-center gap-3 mb-5">
              <div className="p-2 rounded-lg bg-emerald-500/10">
                <ShieldCheck className="w-5 h-5 text-emerald-400" />
              </div>
              <h3 className="text-base font-semibold text-white">Security Status</h3>
            </div>
            <div className="flex items-center gap-3 mb-4">
              <div className="badge badge-success">
                <div className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                Active
              </div>
              <span className="text-sm text-emerald-400">Biometric authentication enabled</span>
            </div>
            <p className="text-sm text-[var(--color-text-muted)] leading-relaxed">
              Your identity is secured with a 512-dimensional facial embedding generated by the
              ArcFace deep learning model. Authentication requires real-time face matching against
              your stored biometric template with liveness verification.
            </p>
          </div>
        </div>

        {/* Quick actions */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 animate-slide-up" style={{ animationDelay: '0.3s' }}>
          <button
            id="btn-re-enroll"
            onClick={() => navigate('/register')}
            className="glass-card-light p-5 text-left flex items-center gap-4 hover:border-blue-500/30 transition-all duration-200 group cursor-pointer"
          >
            <div className="p-3 rounded-xl bg-blue-500/10 group-hover:bg-blue-500/20 transition-colors">
              <ScanFace className="w-6 h-6 text-blue-400" />
            </div>
            <div>
              <h4 className="text-sm font-semibold text-white">Re-enroll Face</h4>
              <p className="text-xs text-[var(--color-text-dim)] mt-0.5">Update your biometric template</p>
            </div>
          </button>

          <button
            id="btn-auth-history"
            className="glass-card-light p-5 text-left flex items-center gap-4 hover:border-indigo-500/30 transition-all duration-200 group cursor-pointer"
          >
            <div className="p-3 rounded-xl bg-indigo-500/10 group-hover:bg-indigo-500/20 transition-colors">
              <History className="w-6 h-6 text-indigo-400" />
            </div>
            <div>
              <h4 className="text-sm font-semibold text-white">Auth History</h4>
              <p className="text-xs text-[var(--color-text-dim)] mt-0.5">View recent authentication logs</p>
            </div>
          </button>
        </div>
      </main>
    </div>
  );
}

function InfoRow({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <div className="flex items-center gap-3">
      <span className="text-[var(--color-text-dim)]">{icon}</span>
      <span className="text-sm text-[var(--color-text-dim)] w-24">{label}</span>
      <span className="text-sm text-white">{value}</span>
    </div>
  );
}
